import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-screen w-screen overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen m-0 p-0 bg-[#F5F5F5] overflow-hidden`}
      >
        <div className="w-full h-full overflow-hidden">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
